//! Canonical home for terminal UI, rendering, and UI-only view state.
pub mod chrome;
pub mod clock;
pub mod focus_caps;
pub mod footer;
pub mod input_editor;
pub(crate) mod palette;
pub mod preflight;
pub(crate) mod render;
pub mod sheet;
pub mod split;
pub mod status_line;
pub mod tui;
pub mod widgets;
pub use crate::app as runtime;
pub use crate::dashboard;
pub use crate::picker;
pub use crate::smoke;
pub use crate::ui::widgets::chat::view as chat_widget;
pub use crate::ui::widgets::models_area::view as models_area;
